def autoclicker():
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    time.sleep(0.01)
    p.click()
    
    